### ISSUE TITLE
Slight change of CCTV text under payment options

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#14]
Hi Matthew,
Regarding the text showing under the payment options (as shown in the attached, would you please change the details to the following:

If you have already gained an SIA course qualification (Door Supervision or Security Guarding) anytime **AFTER 1st April 2021** and can provide your original course certificate, then you may be exempt from the first day of the CCTV course, resulting in you only having to complete the last 3 days.  If so, then please get in touch.

Many Thanks,
Dee
![CCTV text](https://user-images.githubusercontent.com/75130854/110348910-10934200-802a-11eb-8227-1d68482a37f8.jpg)

**Comment by itsmat32143** [comment]
Not a problem will get this changed after work 👍👍

**Comment by DEEHP4** [comment]
No rush mate, Thank you!

**Comment by itsmat32143** [comment]
Done 20:45 08/03/2021
