### ISSUE TITLE
Addition to FAQ answer

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#15]
Hi Matthew,
I hope you're well.

Under the FAQ can you please amend the question & answer, `English isn't my first language.....` to the following:

**English is not my first language.  Will this matter?**
An acceptable level of English language is an official requirement to complete any of our courses.  **This includes English speaking, listening, reading and writing.**  Not only is this important throughout the course, for the completion of forms, reports, understanding of all modules and the many questions in the multiple-choice exams, it is also required in order to work in the industry - communicating with the public, staff, Emergency Services, etc. verbal, non-verbal and written.
**If you attend the course and it is identified that you do not have the acceptable required English skills, it can result in you being refused for the course (or remainder of the course), including the loss of your full course fee.**  Please get in touch with us if you have any queries regarding this.

Thanks mate!
Dee

**Comment by itsmat32143** [comment]
Not a problem will get these done tonight when I get home 👍👍

**Comment by DEEHP4** [comment]
No problem Matthew, although no big rush.

While you're in the FAQ section, could you possibly tweak the **_Does my Training cost include getting the licence_** to **Does my training course fee also include the actual SIA licence (card)?**  and move this question & answer to the very top of the Q&A list.

Also, could you please add an additional Q&A as follows:

**Does the training include any physical activity?**   Yes, the first-aid day of the training for Door Supervision and Security Guarding includes practical training - giving CPR to a training manikin, which involves giving 30 chest compressions over a period of cycles.  Physical activity is also required during the teaching of person-searching demonstrations, scenarios and during the Physical Intervention techniques in the **Door Supervision course**, which also involves safely escorting a person downstairs and upstairs (with colleagues' help).   Please get in touch if you have any queries regarding this, and/or you may want to consult with your doctor if required.


Thanks Matthew

**Comment by itsmat32143** [comment]
No problem will get that done for you too 👍

**Comment by itsmat32143** [comment]
I think that is everything changed 👍👍

**Comment by DEEHP4** [comment]
Perfect Matthew, Thank you, and for doing so quickly.Cheers mate, DeeSent from my Galaxy
-------- Original message --------From: Matty <notifications@github.com> Date: 11/03/2021  00:41  (GMT+00:00) To: "NIWebDesigns/EZTraining.co.uk" <EZTraining.co.uk@noreply.github.com> Cc: DEEHP4 <d.mallon99@virginmedia.com>, Author <author@noreply.github.com> Subject: Re: [NIWebDesigns/EZTraining.co.uk] Addition to FAQ answer (#15) 

I think that is everything changed 👍👍
