### ISSUE TITLE
Addition to courses menu

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#16]
Hi Matthew,
I hope you are well.

When you get a chance (no rush), would you please change the cost of the **3-Day** Top-Up Refresher (screenshot attached) to **£165**   (as it transpires there's more work/costs than I had anticipated).

If you could please also add new separate one for:

- 3 Year Top-Up/Refresher
**£99**
Qualification WITHOUT First-Aid for Door Supervisors and Security Guards from 1st October 2021.  3 Year Refresher `Top-Up` for those that have a suitable First-Aid qualifications (with at least 12mths remaining). 

Any queries please get in touch or give me a call.  Thanks mate!

**Comment by itsmat32143** [comment]
No problem so 2x 3 Year Top-Up/Refresher one with a first-aid certificate and the other without?

**Comment by DEEHP4** [comment]
Yes mate, that's correct. 

3 Year Top-Up/Refresher
**£165**
**x3 Days** Qualification **with First-Aid** for Door Supervisors and Security Guards from 1st October 2021

3 Year Top-Up/Refresher
**£99**
**x2 Days** Qualification ****WITHOUT** First-Aid for Door Supervisors and Security Guards from 1st October 2021, for those who already have a suitable First-Aid qualification (with at least 12mths remaining)

Any queries please get in touch.  Thanks!

**Comment by itsmat32143** [comment]
That should be it done 👍 Have a look and let me know

**Comment by DEEHP4** [comment]
Perfect Matthew, Thank you very much!!

**Comment by itsmat32143** [comment]
No Problem 👍
