### ISSUE TITLE
Tweaks & Additions

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#17]
Hi Matthew,
I hope you are well, and work is going ok.

When you get a chance, although there's no rush, can you please amend (& add) the following:

Change the blue `Book Now` tab to `**Dates & Book**`   _(A lot of people contact me asking for dates, but don't know to click on the `Book Now` tab)._

Change the current course prices as follows:

- 7 days Emergency First-Aid at Work + Door Supervision £265  to: **£275**
- 6 days Door Supervision £195  to **£210**
- 4 days CCTV £175  to  **£179**
- Emergency First-Aid at Work + Security Guarding £245. **This can stay the same at £245.**

**If the following could be tweaked, as well as couple of other Top-Up course options added:**
- 3 Year Top-Up/Refresher £165  Qualification **with First-Aid** for **Door Supervisors only. 3 Days**   to **£195**
- 3 Year Top-Up/Refresher £165  Qualification **WITHOUT First-Aid** for **Door Supervisors only. 2 Days**  to **£139**
- 3 Year Top-Up/Refresher Qualification **with First-Aid** for **Security Guards only. 2 Days**    **£135**
- 3 Year Top-Up/Refresher Qualification **WITHOUT First-Aid** for **Security Guards only. 1 Days**    **£75**

Finally (for now), could you please add this into the FAQ section (General), maybe as the 2nd last question, before "Does the training include any physical activity"?

**Do the courses involve a lot of work?**
Although plenty of guidance and support is given throughout, the courses do involve: `Pre-Course Homework Study` issued to candidates before their course starts, as well as a number of Theory and Practical scenario sessions throughout the course, to include writing, reading, listening and speaking.  
There are a lot of multiple-choice exam questions involved on the last day(s), with the flexible requirement to get at least 75% correct, although with all theory and discussions during the course you will be ready for the exams.  We have a 99% pass rate, and in the unlikely event anyone was to fail an exam, we guarantee a FREE resit of the exam.  

Matthew, please don't hesitate to contact or phone me.  Ps. I've had to increase the costs due to the really extensive additional info', documents, extra days and time spent on all the Doc's & preparation (into late evenings). 

Many Thanks,
Dee

![FAQ addition](https://user-images.githubusercontent.com/75130854/115599432-85b59080-a2d3-11eb-914f-bf44a0fd68a3.JPG)

**Comment by itsmat32143** [comment]
Have a look and let me know what you think you will need to change Paypal buttons for the bottom four boxes

Also would like to add more security to the website by using a service called Cloudflare they offer protection against DDOS attacks and help keep the website as fast as possible I have been implementing it to the other websites that I maintain and it is a very good service this is the link if you would like to check it out

https://www.cloudflare.com/en-gb/plans/

If you would like this added you would need to remove the settings below from your domain account and add the ones below that

ns0.phase8.net
ns1.phase8.net
ns2.phase8.net

colette.ns.cloudflare.com
hugh.ns.cloudflare.com

If you change the settings over to the bottom ones it will use the settings I have in the picture below these should be the same as what is in your account currently

![Untitled](https://user-images.githubusercontent.com/44469185/115614525-ba324800-a2e5-11eb-9aed-b2a81cfc8e93.png)

Thanks
Matthew

**Comment by DEEHP4** [comment]
Hi Matthew,
That's great, Thank you!!

Yes, I will look into this, as the more security (& speed) the better.

When you say "need to remove the settings below from your domain account and add the ones below that", should I get to match the list above exactly as shown?

Thanks & Regards,
Dee

**Comment by itsmat32143** [comment]
ns0.phase8.net
ns1.phase8.net
ns2.phase8.net

In your domain account you should see the three listed above down as hostnames these need to be removed and replaced with the two below do not worry about anything else I will sort it👍🏻

colette.ns.cloudflare.com
hugh.ns.cloudflare.com

**Comment by itsmat32143** [comment]
Also, the padlock at the bottom of each page will take you to an admin panel where I will add in all the information like statistics of views and a detector if the website ever goes down. I added in the link to log issues I hope to populate this side of the website with a lot of statics and useful information to you about the website (Password is - info@eztraining.co.uk)

**Comment by DEEHP4** [comment]
Ok mate,
I'm getting a bit confused.  Firstly, When I go into NamesCo, I'm not sure where to go to find:

Is it any of these sections:
**Change DNS Settings**,  or  **Change Nameservers**

I can't seem to find anything showing:
ns0.phase8.net
ns1.phase8.net
ns2.phase8.net

**Comment by itsmat32143** [comment]
Change Nameservers is where you need to go

**Comment by DEEHP4** [comment]
![NameServers](https://user-images.githubusercontent.com/75130854/115629489-55351d00-a2fa-11eb-9701-6f6d01643b9f.JPG)

The 4 boxes are blank

**Comment by DEEHP4** [comment]
**Are you sure changes will be ok mate, considering their mention of:**
Changing the nameservers for this domain will deactivate any existing services. Only do so if you have been instructed to by your hosting company, or you are experienced in DNS administration.

**Comment by DEEHP4** [comment]
Matthew, 
I'm not sure what's happened to the course menus view, under the Dates/Book Now tab.

It was all fine 10mins ago, but now all changed.

Any idea?

**Comment by itsmat32143** [comment]
Yes, I have done this on all websites it just gives Cloudflare control to protect your domain eztraining.co.uk

Add these two and then save and that should be it done

colette.ns.cloudflare.com
hugh.ns.cloudflare.com

I saw that it should be all fixed now👍

**Comment by itsmat32143** [comment]
After you change the nameservers it will say something like We can't display your DNS information because your nameservers aren't managed by us. this means it has worked 👍

**Comment by DEEHP4** [comment]
Yes, menus now back to normal, Thanks!

So, just before I click on **update**, is this correct?
![SERVER](https://user-images.githubusercontent.com/75130854/115630779-86165180-a2fc-11eb-8b80-e1c177480492.JPG)

**Comment by itsmat32143** [comment]
Yes it should come up after you update with

We can't display your DNS information because your nameservers aren't managed by us.

This means it has worked 👍

**Comment by DEEHP4** [comment]
![UPDATE](https://user-images.githubusercontent.com/75130854/115631101-1b194a80-a2fd-11eb-8e4b-898078f46a96.JPG)

**Comment by DEEHP4** [comment]
I've nothing else to do for now mate?

**Comment by itsmat32143** [comment]
Nope you won't have to do anything else they will sort it out and move it over to Cloudflare and when they do I will add the security in 👍👍

**Comment by DEEHP4** [comment]
Great stuff.  Thanks Matthew, I really appreciate your prompt help as always.
I'll be in touch.  Good Night !!

**Comment by itsmat32143** [comment]
That's everything moved over so will add the security now 
Not a problem glad to be able to help 

Goodnight
