### ISSUE TITLE
Request for slight tweaks

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#22]
Hi Matthew,
I hope you are well and work is going ok.

Could you possibly tweak the course costs on the website for me at some stage?

I was also thinking if the following could go somewhere into each of the course boxes (top or bottom), instead of showing once located under the boxes:
On booking a course I confirm that I have read and agree to the [Terms and Conditions](https://eztraining.co.uk/FAQ.html#toggle1-1e) which can be found in the FAQ section

Any queries please get in touch.

Thanks & Regards,
Dee

**Comment by itsmat32143** [comment]
Yes not a problem what are you looking the pricing edited to?

**Comment by DEEHP4** [comment]
Ok mate, I was looking at changing the following (due to increases in exams/books/services....), although no changes to the Top-Up courses:
  
4-day CCTV from £179 to **£215**    
5-day Security Guarding (with EFAW) from £245 to **£265**   
6-day DS course (without EFAW) from £210 to **£235**     
7-day DS course (with EFAW) from £275 to **£295**. 

Any queries please get in touch.

Ps. No big rush for this Matthew.

Thanks & Regards,
Dee

**Comment by itsmat32143** [comment]
Dead will get that squared away for you should be Monday night I will have it done by 👍🏻

**Comment by DEEHP4** [comment]
Ok Matthew.  Thank you!

**Comment by itsmat32143** [comment]
Another tweak Matthew.  In the FAQ section regarding the requirement for the first-aid, I've added a few extra words, which now reads:    Can I just do the Door Supervision (or Security Guarding) course without doing the First-Aid?
Only if you have a suitable and valid First-Aid qualification with at least 12 months remaining on it, and you can produce the original certificate (for us to check and photocopy on the first morning of your security course). This can include: Emergency First-Aid at Work (EFAW),  First Aid at Work (FAW); First Person on Scene (FPOS); First Response Emergency Care (FREC). A basic online first-aid course (with no classroom theory and  practical training involved) will not be suitable.  Further details can be found via this link:
