### ISSUE TITLE
Minor tweaks (continued)

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#23]
Hi Matthew,
Can you please make the following changes, although no rush:

In the FAQ:   
Amend the answer for _**How much does the SIA licence cost and how long does it last for?**_  to: As from the 6th April 2023 the SIA licence is reduced from £190 to **£184** (payable to the SIA) and lasts for 3 years. You may be required to complete a Top-Up refresher course in order to renew your licence.  The new replacement licence will then cost another £184. (Note: If you have a secondary SIA licence with at least 4 months remaining on it, then your primary licence will cost half=price (£92). For example, you have a Security Guarding (or Door Supervisor) as a primary licence, as well as CCTV as a secondary licence.  

Can you add the following (to show under this SIA licence cost Q+A): 
Do I need to provide form of identification for a course?   Yes, please see the list under **[What to bring](https://eztraining.co.uk/FAQ.html#toggle1-1e)**  Failure to provide the acceptable forms of identification can result in you being unable to do the multiple-choice exams and finish the course, as well as losing your full course fee.

Can you please remove the questions & answer from the list, as it's not important now.

![Please remove from FAQ](https://user-images.githubusercontent.com/75130854/222004426-cfd37a73-b6a1-4e71-8f1a-9966d1e14f48.JPG)

I hope this is clear mate, and any questions please get in touch.

Many Thanks,
Dee

-

**Comment by DEEHP4** [comment]
Sorry Matthew,
For that first part, it might be better saying:
How much does the SIA licence cost and how long does it last for? 
As from the 6th April 2023 the SIA licence is reduced from £190 to £184 (payable to the SIA) and lasts for 3 years.  When you go to renew your licence, ideally before the 3 years is up _(to allow time for your new application being processed)_, you may be required to complete a Top-Up refresher course. The new replacement licence will then cost another £184. (Note: If you have a secondary SIA licence with at least 4 months remaining on it, then your primary licence will cost half=price (£92). For example, you have a Security Guarding (or Door Supervisor) as a primary licence, as well as CCTV as a secondary licence.

**Comment by itsmat32143** [comment]
No problem will get this sorted for you!

**Comment by itsmat32143** [comment]
Will have these done for you tomorrow night apologies got stuck in work is there anything else you need updated as I will be way 5th to 10th with limited to no internet???

**Comment by DEEHP4** [comment]
No worries Matthew, as there's no big rush.  Just when you're able to mate.

Thank you!
Dee

**Comment by itsmat32143** [comment]
That should be everything sorted have a look and see what you think
