### ISSUE TITLE
Slight tweak to 5-day Security Guarding description

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#24]
Hi Matthew,
I hope you are keeping well.

I've just noticed (under the blue `Dates & Book` tab) that the 5-day SG course mistakenly shows "For those who already have an existing First-Aid qualification).

Can you please change this to show: "Security Guarding + Emergency First-Aid at Work" as the title, then under the cost ideally showing: "**SIA requirement from 1st April 2021 to have First-Aid. This course allows you to work in all Security Guard roles (to include shops, office-blocks, factories, etc".**

Any queries please get in touch.

Many Thanks,
Dee

**Comment by itsmat32143** [comment]
Currently in work but will get this sorted for you at 17:00 today 👍🏻

**Comment by itsmat32143** [comment]
Changes done let me know if you are happy with the changes 👍🏻

**Comment by DEEHP4** [comment]
PERFECT Matthew,
Thank you very much, I appreciate it.

Kind Regards,
Dee

**Comment by itsmat32143** [comment]
No worries anything else just fire it across
