### ISSUE TITLE
SPF / DFIM...

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#25]
Hi Matthew,
I hope you are well.

Can you possibly help with the following:
Over the past months I've been getting loads of my email sent to people with gmail (or googlemail) accounts rejected by Google, as their systems automatically suspect the emails are advertising or spam, even though they're not.

I got in touch with domain provider, NamesCo, and they informed me over the phone that things seem to be correct on their side, but that the SPF setting need to be corrected on Cloudflare which apparently may be causing the problem.

I've pasted below the guidance instructions Namesco have sent me, which I hope makes sense to you, if you could please let me know, and let me know if there's any details you require.

Thanks mate,
Dee

-----Original Message-----
From: Namesco Support Team 
Sent: 30 May 2023 16:51
To: D.MALLON
Subject: Re: Support Enquiry Ref: [SU18687648]

Hi, 
Thank you for getting in touch with us regarding your emails being sent to recipient junk or spam folders. 

We have investigated the issue that you have reported and can inform you of the following: 

Your domain DNS settings contain an incorrect SPF record. This record is important in preventing your emails from being filtered out as spam messages by verifying that the emails you are sending have been sent from a valid and genuine email server. 

We would normally update this record to the correct SPF for you, but your domain is currently using third party nameservers which prevent us from editing your DNS records. 

You will need to ask whomever manages your DNS records for you to add the following in to your DNS settings as a TXT type record: 

v=spf1 include:spf.hosts.co.uk ~all 

Once this has been added, you will need to allow up to 24 hours for this to completely embed and complete a process known as propagation. 

Information about propagation can be found here: 

https://www.names.co.uk/support/articles/what-is-propagation-and-how-does-it-affect-me/ 

You can find more information about why a valid SPF record is important here: 

https://www.names.co.uk/support/articles/what-is-an-spf-record/ 

We hope that this information is of use to you. 

If you have any further problems or queries then please update this enquiry through the "Technical Support" section of your Control Panel, and we will be happy to help. 

** PLEASE NOTE, THIS IS A NO-REPLY ADDRESS ** 

Kind Regards,
Support Team
Namesco Limited

**Comment by itsmat32143** [comment]
The TXT Type mentioned in the guidance has been in place since the website was moved from godaddy to myself leave it with me and I will look into this tonight for you 👍🏻😋

**Comment by DEEHP4** [comment]
Ok.  I thought the issue was on the NamesCo side, but he said it seemed to be relating to Cloudflare (even though I didn't mention Cloudflare once).  

Thank you!

**Comment by DEEHP4** [comment]
Did you have any joy with this yet mate? 

All my emails being sent to gmail addresses are getting continuously  rejected and bouncing back to me, with the following message:
SMTP error from remote mail server after end of data:
    550-5.7.26 This mail is unauthenticated, which poses a security risk to the
    550-5.7.26 sender and Gmail users, and has been blocked. The sender must
    550-5.7.26 authenticate with at least one of SPF or DKIM. For this message,
    550-5.7.26 DKIM checks did not pass and SPF check for [eztraining.co.uk] did
    550-5.7.26 not pass with the ip address. The sender should visit
    550-5.7.26  https://support.google.com/mail/answer/81126#authentication for
    550 5.7.26 instructions on setting up authentication. gs30-20020a1709072d1e00b00965e3a8dd17si594814ejc.542 - gsmtp

I've checked and read the Google support & guidance details regarding this, but NamesCo have confirmed the details are correct on their side, and that the `**SMTP Authenticated**` is confirmed too, but as previously mentioned, said that CloudFlare seems to be causing the issue, although I don't have too much faith it is.

It's so bad I'm now having to ask people to create a Yahoo or Hotmail email address in order to send/receive details.

Thanks,
Dee

**Comment by itsmat32143** [comment]
Could you provide me with the email and password login to the email?

**Comment by DEEHP4** [comment]
The NamesCo email address & password, which also shows the DNS setting etc?Sent from my Galaxy
-------- Original message --------From: Matthew ***@***.***> Date: 06/06/2023  15:18  (GMT+00:00) To: "NIWebDesigns/EZTraining.co.uk" ***@***.***> Cc: DEEHP4 ***@***.***>, Author ***@***.***> Subject: Re: [NIWebDesigns/EZTraining.co.uk] SPF / DFIM... (Issue #25) 
Could you provide me with the email and password login to the email?

**Comment by DEEHP4** [comment]
Matthew,
I contacted NamesCo again there and the tech' guy was adamant that the following needs to be inserted into the CloudFlare DNS settings, as a TXT type record:    **v=spf1 include:spf.hosts.co.uk ~all**

**Comment by DEEHP4** [comment]
Ensuring the **~all** is included at the end, as he said it doesn't seem to include this when he done a domain check.

**Comment by DEEHP4** [comment]
Hi Matthew,
Did you have any joy with this?

The sending to gmail addresses is still an ongoing problem every day/night, and they're all just being rejected.

Regards,
Dee

**Comment by itsmat32143** [comment]
SPF is correctly set up on our end I have been back and forward with cloudflare and they have comfirmed it is visible for namesco to see the only thing would be to try DFIM which I would need your login to your email and password to activate the setting and set it up it seems to be a issue with namesco reading the SPF inches domain but DFIM is a different protocol and had not been set up before so might be worth trying it

**Comment by DEEHP4** [comment]
This is what the DFIM settings (TXT file) are currently showing on NamesCo
(DNS settings):

v=DKIM1;k=rsa;s=email;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+4J16HejaPxOU
qvC60vHK4kMK41L/+JQernAMeXAts6TmQsDeVcpAjy/doxKAA+NIwGgBKggLV7NKRAwlU6WS7zUj
cHSwf2bjbUK0JYQZi26TV7WdtorZdI1vvA0O8MReWeoq5vSmjfvLQ2DId5Q05aqh4TvA//hXavfp
l05RrwIDAQAB

 

Regards,

Dee

**Comment by DEEHP4** [comment]
Thanks again Matthew, 

I appreciate all your help.

 

Cheers,

Dee
