### ISSUE TITLE
Addition to FAQ section

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#27]
Hi Matthew,
I hope you are well.

Can you please add the following to the FAQ Terms & Conditions section of the website, maybe 2nd from the top if possible:
Is there a course cancellation fee?

Yes.  Irrespective of how much notice is given for cancelling a course (even if weeks or months in advance), there will be a 10% fee deducted from the refund amount.  This is due to PayPal charging EZ Training a transaction fee when a booking is made and when any refund is given. Therefore please ensure the course dates you are choosing suit you.  There is no charge however if you just want to postpone your course to a later date (with at least 7 working days notice given).

**Comment by itsmat32143** [comment]
No problem 👍

**Comment by itsmat32143** [comment]
done 11/08/2023 21:29
