### ISSUE TITLE
Updated links to SIA `How To` videos

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#28]
Hi Matthew,
Can you please also update the videos in the FAQ section:

**How do I register for an personal SIA online account?** https://www.youtube.com/watch?v=OdeS4h8hhhw&t=20s

**Submitting an online SIA licence application form (when I have successfully passed my course)**   https://www.youtube.com/watch?v=Pllx2fOpJJk

**How Do I Check The Status Of My SIA Application?**  https://www.youtube.com/watch?v=S3_MgnwMaTM

**Requesting a replacement SIA licence card?**   https://www.youtube.com/watch?v=TrsQXYMM7Uk&list=PLm-kj8Pq_32svcByiq4Q41Ig4TeuOsiTF&index=8
 
Thank you!
Dee

**Comment by itsmat32143** [comment]
Yeah no problem 👍
