### ISSUE TITLE
Price corrections (x2)

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#29]
Hi Matthew,
The tweaks made earlier caused havoc on the PayPal coding, which I've spend the last two hours on.  I just wanted to change the notes to `Please email us`, as when it shows `Dates coming soon` some people have eventually contacted me after waiting and waiting thinking dates were about to be displayed, but not necessarily.

The PayPal coding was worse than ever before for some reason.  Maybe something PayPal has changed over the past while regarding their layout.

However, I think it's all sorted now, but would you please correct the pricing for the two showing in the attached screenshot.

Thanks mate,
Dee
![Price corrections](https://github.com/NIWebDesigns/EZTraining.co.uk/assets/75130854/724a1918-4bc2-424f-8255-412d9f2eca9b)

**Comment by itsmat32143** [comment]
Pricing all sorted seen a few issues with the PayPal code imported last night 
![Screenshot_20230812_072755_Chrome](https://github.com/NIWebDesigns/EZTraining.co.uk/assets/44469185/6a334a6f-401b-4c9b-85e1-3b0339c5de54)
Will take a look at the PayPal code tonight and get it fixed up don't be spending that long on it that's what I am here for if you have any issues with uploading pricing just fire me the code over and text me and I'll put it straight up as I can do small stuff like that on my phone without laptop 👍

**Comment by DEEHP4** [comment]
Ok mate, Thank you very much !!

Kind Regards,
Dee
