### ISSUE TITLE
SSL certificate issue

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#30]
Hi Matthew,
I hope you got a bus into town ok & home too.

It seems that the site is having an issue from this afternoon regarding the SSL certificate.  See screenshot attached.  Can you please have look into this.

Thanks,
Dee

![SSL cert' problem](https://github.com/NIWebDesigns/EZTraining.co.uk/assets/75130854/058f5523-3598-4e1f-93f7-8ca78466a0b9)

**Comment by itsmat32143** [comment]
Should have auto resolved seems to have done so it could have been your browser as it remembers the website for so long which could by why you still seen the error as it was using the memory saved in the computer will keep a eye

On another note you said about the mock quizzes being bad with some of the questions and answers what about having you own?

https://forms.gle/VL5PW2aCtuffZaJK6

**Comment by DEEHP4** [comment]
Thanks very much mate.Yes, a good idea.  Maybe I could gradually piece a few mocks together, for Security Guarding, Door Supervision & Top-Ups, CCTV.Sure we can talk about it soon.Cheers Matty,Dee
-------- Original message --------From: Matthew ***@***.***> Date: 13/12/2023  23:58  (GMT+00:00) To: "NIWebDesigns/EZTraining.co.uk" ***@***.***> Cc: DEEHP4 ***@***.***>, Author ***@***.***> Subject: Re: [NIWebDesigns/EZTraining.co.uk] SSL certificate issue (Issue #30) 
Should have auto resolved seems to have done so it could have been your browser as it remembers the website for so long which could by why you still seen the error as it was using the memory saved in the computer will keep a eye
On another note you said about the mock quizzes being bad with some of the questions and answers what about having you own?
https://forms.gle/VL5PW2aCtuffZaJK6
