### ISSUE TITLE
Removal of SG 1-day course option

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#31]
Hi Matthew,
I hope you are well.

Can you please remove the option under the Dates & Book tab as shown attached.

Also, can you please add the following to a separate paragraph at the bottom of the existing English Language Skills paragraph (also attached):  

As required by the SIA and Awarding Body, all course candidates are required to complete a short **Basic Level 1 English Literature Test Paper** on the first morning of the Security  course to help assess if they have at least the basic skills of reading and writing in English language.  If the candidate does not accept the minimum pass mark of this Basic Level 1 test (or poor English speaking skills), then they will be unable to proceed with the course and will lose their course fee.

Any queries please get in touch.

Many Thanks,
Dee

![SG 1-day option](https://github.com/NIWebDesigns/EZTraining.co.uk/assets/75130854/6187aa2a-0df5-4c44-9f5d-4bfd74bd0213)
![English Language Skills](https://github.com/NIWebDesigns/EZTraining.co.uk/assets/75130854/0e161a57-0767-460d-81c2-766b37cd8e31)

**Comment by itsmat32143** [comment]
Currently travelling back home from holiday today will get this squared away for you tomorrow 👍👍

**Comment by DEEHP4** [comment]
Sorry to disturb you mate.  I hope you had a great holiday. 
Just a pity you're coming back to our cold/wet weather.

Thank you!
De

**Comment by itsmat32143** [comment]
All sorted! have a look and let me know

**Comment by DEEHP4** [comment]
Perfect, Thank you mate.Sent from my Galaxy
-------- Original message --------From: Matthew ***@***.***> Date: 10/02/2024  16:45  (GMT+00:00) To: "NIWebDesigns/EZTraining.co.uk" ***@***.***> Cc: DEEHP4 ***@***.***>, Author ***@***.***> Subject: Re: [NIWebDesigns/EZTraining.co.uk] Removal of SG 1-day course option (Issue #31) 
All sorted! have a look and let me know
