### ISSUE TITLE
Addition to FAQ section (English skills)

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#32]
Hi Matthew,
I hope you are well.

As I've had a couple of issues recently regarding English Skills, can you please make a tweak to the section (as shown attached), to show the following:

As required by the SIA and Awarding Body, all course candidates aiming to work in the private security industry are required to complete a short Basic Level 1 English Literature Test Paper on the first morning of the Security course (including Top-Up courses) to help assess if they have at least the basic skills of reading and writing in English language. This includes having to write a paragraph with good grammar and punctuation.  If the candidate does not achieve the minimum pass mark of this Basic Level 1 test (and/or has poor English **speaking** skills), then they will be unable to proceed with the course and will lose their course fee.

As well as being able to complete the course, it is also to assess if the candidate has the required English skills (reading, writing, speaking & listening) in order to work in the security industry (dealing with people, two-way radios and phones,, emergency services, reports and log-books etc).

Please get in touch via email to **info@eztraining.co.uk** if you have any queries.

![Screen Shot 02-27-24 at 07 16 PM](https://github.com/NIWebDesigns/EZTraining.co.uk/assets/75130854/4bb428dd-9e83-49c1-a69b-9cf08de67eb9)

**Comment by DEEHP4** [comment]
Matthew,
Sorry, I also meant to ask if the title of the question could also be changed from `English is not my first language. Will this matter?` to:
**PLEASE READ: Strict requirement of English language skills for courses**

**Comment by itsmat32143** [comment]
On it give me a few mintutes

**Comment by DEEHP4** [comment]
Ok mate, Thank you.

I'm thinking it might also be good to add a brief note to the pop-up box (when clicking on **Dates & Book**), so that it shows:
Terms and Conditions

On booking a course I confirm that I have read and agree to the [Terms and Conditions], **which includes English Language skills requirement**  (https://eztraining.co.uk/FAQ.html#top) which can be found in the FAQ section.

**Comment by itsmat32143** [comment]
First bit is done on the second bit now :-)

**Comment by itsmat32143** [comment]
Have a look at that and see what you think! :-)
