### ISSUE TITLE
Pricing not fully working on website

### ISSUE THREAD

**Issue by DEEHP4** [NIWebDesigns/EZTraining.co.uk#33]
Hi Matthew,
I hope you are keeping well.

A couple of the course (PayPal) booking tabs on the website are not working = The 7-day Door Supervision (with first-aid), as well as the 6-day Door Supervision (without first-aid).

I then went into `Edit` and re-pasted the PayPal button code into each part (in the Pricing section here), and saved it, but it still isn't taking, even after clicking on the refresh tab a load of times.  It's not saving any of my changes at all, even text.

As you know, I've tweaked the text this way a load of times this exact same way, but it's just not doing anything now.

Any ideas what could be causing this?

Regards,
Dee

**Comment by itsmat32143** [comment]
That's it fixed should have no issues now I have put up what you tried to upload yesterday to the site👍

**Comment by DEEHP4** [comment]
Excellent, Thank you Matthew.

 

Kind Regards,

Dee
